version: "3.4"
x-logging:
  &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  taiko-node-dashboard:
    image: wolfderechter/taiko-node-dashboard:latest
    ports:
      - "8082:80"
  taiko-node-systeminfo:
    image: wolfderechter/taiko-node-systeminfo:latest
    ports:
      - "3009:3009"
